apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/qbritton/cis-92:milestone-4.3
    env:
    - name: SECRET_KEY
      value: "mysecretkey"
    ports:
    - containerPort: 80